### ISSUE TITLE
radiko動いていない？

### ISSUE THREAD

**Issue by hasegawa-tomoki** [yayugu/net-radio-archive#11]
radiko、動いていますか？
正しい動作がまだ分かっていなく、動いているのかもしれないのですが、
lib/radiko/scraping.rbの`http://radiko.jp/v2/api/program/station/weekly`は
404になっている様です。

（データベーステーブルは db:migrate で生成されなかったので、db/schema.sql
を流しています。これが原因かもしれませんが…。）

**Comment by yayugu** [comment]
ご報告ありがとうございます。

2点ご確認いただきたい点があります。
- このソフトを使用しないでブラウザからアクセスする場合にサーバーのIPからradikoを試聴できるか（エリア内か）
- config/settings.ymlの設定のチャンネルコードは適切か

このページが参考になります。
http://d.hatena.ne.jp/zariganitosh/20130214/radiko_keyword_preset

---

> （データベーステーブルは db:migrate で生成されなかったので、db/schema.sql
> を流しています。これが原因かもしれませんが…。）

これは今のところそれが正しいセットアップ方法です（あとでドキュメント修正 or migrateできるようにします...）

**Comment by hasegawa-tomoki** [comment]
ブラウザからの視聴、OKでした。
`http://radiko.jp/v2/api/program/station/weekly`はちゃんとしたチャンネルコードを
渡さないと404を返すのですね。すみません！

そして、config/settings.ymlは(archive|working)_dirしか触っていませんでした。
頂いたURLとsettings.ymlを見て理解しました。settings.ymlに設定したチャンネルコードの
ワークディレクトリが出来るのですね。

すみません、ろくに調べもせず。引き続きセットアップしてみようと思います！

**Comment by yayugu** [comment]
いえいえ、こちらとしても十分なドキュメント用意できていないので、またお気軽どうぞ！
