### ISSUE TITLE
不定期にradikoの録音に失敗する

### ISSUE THREAD

**Issue by warpzone** [yayugu/net-radio-archive#21]
時間帯も局も不定なのですが、録音に失敗することがあります。
rec_one の出力はこんな感じです。

rtmpdump は6/12時点のソースをgit cloneしてビルドしています。

E, [2015-06-13T17:00:22.740065 #16306] ERROR -- : rec failed. job:65, exit_status:pid 16323 exit 1, output:RTMPDump v2.4
(c) 2010 Andrej Stepanchuk, Howard Chu, The Flvstreamer Team; license: GPL
WARNING: No application or playpath in URL!
WARNING: Can't resume live stream, ignoring --resume option
Connecting ...
WARNING: Trying different position for server digest!
INFO: Connected...
ERROR: RTMP_ReadPacket, failed to read RTMP packet body. len: 16354644

**Comment by yayugu** [comment]
報告いただきありがとうございます。

同様の現象は自分の方でも起きています。

対策はあまりよいものが思いついていなくて、
回線などが原因であれば複数のサーバーで同一コンテンツを録音すれば失敗確率は下がりそうですが、
もし原因が回線などではなく、radikoサーバー側の問題だったりrtmpdumpのコードの問題だったりした場合には結局失敗してしまいますし…

リアルタイムで取得し続けている以上、たまに失敗するのは仕方ないのかなと諦めています。

**Comment by warpzone** [comment]
なるほど、 ”No application or playpath in URL!" とあるのでてっきり rtmpdump にうまく
URL が渡せていない場合があるのかと思ってました。
