### ISSUE TITLE
30日より短い日数でworking filesを消せるようにして欲しい

### ISSUE THREAD

**Issue by akimasa** [yayugu/net-radio-archive#25]
ブロックストレージの容量が少ない環境（Raspberry PiかVPSなので容量が30GB程度）で使いたいので、7日とかでworking filesが消えるようにして欲しいです。設定で削除するまでの日数を設定できる感じです。
ちなみに、archive_dirの内容は毎日、他の場所（手元のHDDかAmazon S3やBackblaze B2）に転送する予定なのでブロックストレージの容量が少なくてもやっていけるかと思います。

Rubyはあまり書いたことが無いので、Pull Requestが出来るか、自信が無いです。対応していただけるとありがたいです。よろしくお願いします。

**Comment by yayugu** [comment]
取り込みました

**Comment by akimasa** [comment]
ありがとうございます！
