### ISSUE TITLE
hibikiのダウンロードが終わらない

### ISSUE THREAD

**Issue by warpzone** [yayugu/net-radio-archive#29]
README で紹介されている static link 版の ffmpeg を使用して、net-radio-archive を
最新に更新して hibiki をダウンロードしようとしていますが、ffmpeg のプロセスがいつまでも
残り続けてダウンロードが終わりません。

working_dir にはそれなりのサイズの mp4 が保存されていますが、壊れて再生できません。

作者さんの環境ではいかがでしょうか？

**Comment by yayugu** [comment]
ffmpegであったりrtmpdumpであったりはかなり失敗します。
だいたいの場合retry（一日間隔で動きます）すれば直るので、放置しておくといいかと。

ただrtmpdumpはそのようにzombie化したprocessを24時間後くらいに強制終了させているのですがffmpegはそうなっていないので、今度直そうかと思います。
