### ISSUE TITLE
radikoの録音ができない

### ISSUE THREAD

**Issue by pocono1** [yayugu/net-radio-archive#33]
radikoの仕様変更により下記のpathが404エラーとなってしまい、radikoの録音ができないようです。

SWF_URL = 'http://radiko.jp/player/swf/player_4.1.0.00.swf'

**Comment by warpzone** [comment]
プルリク投げました。

#34

**Comment by yayugu** [comment]
ご報告ありがとうございましたmm
またなにかお気づきのことあればおねがいしますね
