### ISSUE TITLE
らじるらじるのScraping用のアドレスについて

### ISSUE THREAD

**Issue by pocono1** [yayugu/net-radio-archive#40]
表題のアドレスが

http://cgi4.nhk.or.jp/hensei/api/sche-nr.cgi?tz=all&ch=net#{ch}&date=#{today}
から
http://cgi4.nhk.or.jp/hensei/api/sche-nr.cgi?tz=all&ch=net#{ch}&#{today}
へ変わっているようです。

Pull requestが投げられない環境のためIssuesで報告させていただきます。

**Comment by yayugu** [comment]
ありがとうございます！
修正しました
