### ISSUE TITLE
AGON-PのHTMLが変わったようでスクレイピングに失敗する

### ISSUE THREAD

**Issue by spool6810** [yayugu/net-radio-archive#46]
AGON-PremiumのHTMLが変わったようで、新規のスクレイピングが失敗しています。
ruby, nokogiriは私は使ったことがないのであまりきれいじゃないかもしれませんが、パッチはこんな感じです。

        --- lib/agonp/scraping.rb.orig	2017-09-14 14:20:35.971562691 +0900
        +++ lib/agonp/scraping.rb	2017-09-14 14:13:38.902735637 +0900
        @@ -1,3 +1,4 @@
        +# coding: utf-8
         module Agonp
           class Program < Struct.new(:title, :personality, :episode_id, :price)
           end
        @@ -30,24 +31,24 @@
             end
         
             def parse_programs(page)
        -      page.search('.program-list-row').map do |program_row|
        +      page.search('.search-results__data-wrapper').map do |program_row|
                 parse_program(program_row)
               end
             end
         
             def parse_program(program_row)
        -      title = program_row.css('.program-list-row-title').first
        -                  .children
        -                  .select {|c| c.text?}
        -                  .reduce('') {|memo, c| c.text}
        -                  .strip
        -      episode_id = program_row.css('a').first.attr('href')
        -                       .match(%r{episodes/view/(\d+)})[1]
        +      title = program_row.css('.search-results__title').first
        +              .children
        +              .inner_text.strip
        +              .sub(/無料\s+/,'')
        +              .sub(/^\s+/,'')
        +              .sub(/\s+$/,'')
        +      episode_id = program_row.css('a').attr('href').text.match(/programs\/view\/(\d+)/)[1]
               Program.new(
                   title,
        -          program_row.css('.program-list-row-participants').first.text.strip.gsub('／', ' '),
        +          program_row.css('.search-results__personality').first.text.strip.gsub('／', ' '),
                   episode_id,
        -          program_row.css('.program-list-row-price').first.text.strip,
        +          program_row.css('.search-results__price').first.text.strip
               )
             end
           end

**Comment by yayugu** [comment]
ありがとうございます！
動作確認して取り込みたいと思いますので

**Comment by yayugu** [comment]
ありがとうございます！
動作確認して取り込みたいと思いますのでpull-requestの形にしていただけますか
