### ISSUE TITLE
音泉のリニューアル

### ISSUE THREAD

**Issue by ttytb** [yayugu/net-radio-archive#61]
音泉のリニューアルに伴って、録音できなくなっています。

production.logにエラーが記録されています。
E, [2020-07-28T13:04:11.937247 #61762] ERROR -- : onsen scraping error: http://www.onsen.ag/app/programs.xml, 307

URLにアクセスすると404になるので、場所が変わったみたいです。

**Comment by yayugu** [comment]
https://github.com/yayugu/net-radio-archive/pull/62
こちらで直ったとおもいます
