### ISSUE TITLE
ChromeだとA&Gのmp4ファイルのみ再生できない

### ISSUE THREAD

**Issue by yayugu** [yayugu/net-radio-archive#9]
Chrome 40

Mac, Windowsともに確認

他のmp4などは再生できるためファイルが良くない？ なぞ
Firefox、mobile safariだと問題なし。他ブラウザは試してない

**Comment by yayugu** [comment]
https://www.chromium.org/audio-video

HE-AACに対応していないせいな気がしてきた。（未確認）
そうするとただでさえひどい音質なのに再エンコ必須になる。つらい

**Comment by yayugu** [comment]
すこしググったらHE-AAC対応してるっぽい

**Comment by yayugu** [comment]
HE-AACv2に対応していないのが原因。とはいえこれnet-radio-archiveで対応するべきなのか微妙な問題だ。
とりあえず直したい人はaudioのコーデックをAAC-LCとかで再エンコするスクリプト書くといいんじゃないでしょうか

**Comment by YuheiNakasaka** [comment]
もうcloseしちゃってますがこのissueにぶつかった人のために。

https://github.com/yayugu/net-radio-archive/blob/1df4904961e70990358c23d9376b698963361048/lib/main.rb#L63

acodecのところを下記のようにcopyからaacに書き換えれば問題なく動くmp4が生成されるようになります。

```
-acodec aac
```

ただcopyで生成したファイルよりファイルサイズが大きくなるなど問題はありますが。

参考まで。
